# Generated by Django 5.1.1 on 2024-10-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('salary', 'Salary Account'), ('student', 'Student Account'), ('savings', 'Savings Account'), ('current', 'Current Account'), ('joint', 'Joint Account')], default='savings', max_length=20),
        ),
    ]
